version: '0.1'

services:
  dev:
    environment: 
        - test=test
        - DATABASE_URL=postgres://postgres:postgres@postgres:5432/swadisth
        - DEV_DATABASE_URL=postgres://postgres:postgres@postgres:5432/swadisth
        - TEST_DATABASE_URL=postgres://postgres:postgres@postgres:5432/swadisth
        - NODE_ENV=development
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./:/app

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
