version: '0.1'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
      args: 
        test: test
    ports:
      - 4000:4000
    image: swaditsh-backend-dev:latest
    volumes:
      - ./:/app

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
