version: '0.1'

services:
  dev:
    build:
      context: .
    ports:
      - 4000:4000
    environment: 
      - test=test
      - DATABASE_URL=${DATABASE_URL}  
      - DEV_DATABASE_URL=postgres://postgres:postgres@postgres:5432/swadisth
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
    volumes:
      - ./:/app

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
