name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      -
        name: Build Image
        run: docker build -t swaditsh-backend-dev:latest . --target test
      -
        name: List local images
        run: docker images --all
      -
        name: Push Build
        run: docker push swaditsh-backend-dev:latest ${{ secrets.DOCKER_HUB_USERNAME }}/swaditsh-backend-dev:latest
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/swaditsh-backend-dev:latest
      # -
      #   name: Run database 
      #   run: docker compose -f docker-compose.dev.yml run -d postgres
      # -
      #   name: Push Build
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/swadisht-backend:latest
